services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8001:8000"
    environment:
      APP_NAME: ai-mems
      DATABASE_URL: sqlite:////data/memes.db
      STORAGE_DIR: /data/storage
      ALLOW_GENERATION: "true"
      AI_PROVIDER: local_text
      # OPENAI_API_KEY: ""
    volumes:
      # bind-mount: используем твои локальные файлы/папки
      - ./backend/storage:/data/storage
      - ./backend/memes.db:/data/memes.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE: http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped
